CREATE DATABASE IF NOT EXISTS checkpoint_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE checkpoint_db;

CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE games (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_game_id VARCHAR(100) NULL,
  source ENUM('rawg','manual') NOT NULL,
  title VARCHAR(255) NOT NULL,
  cover_url TEXT NULL,
  release_date DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_external_source (external_game_id, source)
) ENGINE=InnoDB;

CREATE TABLE user_games (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  game_id BIGINT UNSIGNED NOT NULL,
  platform VARCHAR(100) NOT NULL,
  status ENUM('plan_to_play','playing','completed') NOT NULL DEFAULT 'plan_to_play',
  notes TEXT NULL,
  total_playtime_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_game_platform (user_id, game_id, platform),
  CONSTRAINT fk_user_games_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_games_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE progress_checkpoints (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_game_id BIGINT UNSIGNED NOT NULL,
  checkpoint_date DATE NOT NULL,
  note TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_checkpoints_user_game FOREIGN KEY (user_game_id) REFERENCES user_games(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE play_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_game_id BIGINT UNSIGNED NOT NULL,
  started_at DATETIME NOT NULL,
  paused_at DATETIME NULL,
  ended_at DATETIME NULL,
  accumulated_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  duration_seconds BIGINT UNSIGNED NULL,
  status ENUM('running','paused','finished') NOT NULL DEFAULT 'running',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sessions_status (status),
  CONSTRAINT fk_sessions_user_game FOREIGN KEY (user_game_id) REFERENCES user_games(id) ON DELETE CASCADE
) ENGINE=InnoDB;
